### ISSUE TITLE
2021-05-02 23:41:38.444 +09:00 [ERR] [] Bot wasn't started: API Key isn't allowed

### ISSUE THREAD

**Issue by Crazycar7** [WickHunter/Wick-Hunter#1]
2021-05-02 23:41:38.444 +09:00 [ERR] [] Bot wasn't started: API Key isn't allowed

error...
In other bots it works fine with the same API key value.
What is the problem?

**Comment by Shayano** [comment]
You need to apply for access 
More information on the discord server:
https://discord.gg/mJyNmaVF

**Comment by Jamhead90** [comment]
I am having same issue, any chance for the discord invite, as it has expired?
